### ISSUE TITLE
SMS survey logic not being followed correctly

### ISSUE THREAD

**Issue by onepoint** [OnePointGlobal/OnePoint-Global-SMS-Services#10]
CustomerID 39610595 history shows that the survey logic included a random macro which should have led to this respondent being sent a mobile web link but the question was never sent out. This is the same for all recent customers where this route is followed in the survey.

**Comment by dougmorris** [comment]
I can confirm the issue and am looking into it.

**Comment by dougmorris** [comment]
This has been resolved. The logic was taken from the Web Surveys engine and has been modified to support SMS survey correctly.
