### ISSUE TITLE
SMS survey is continuing without providing any response

### ISSUE THREAD

**Issue by onepoint** [OnePointGlobal/OnePoint-Global-SMS-Services#16]
While testing surveyID 42305 it was observed that the survey intro and Q1 were sent out but the next question and then completion were also sent out without any response being sent. Looking at the QA record for customerID 39612240 it has taken the answer as "2" for every question.

**Comment by dougmorris** [comment]
This survey was created after the startup of the new platform on the morning of 18/4/2018. This mean that the actions were not copied across. There was a bug relating to macro evaluation (specifically the ${brand} macro), but it did not cause this issue. Now the survey script has been changed to include the actions it is functioning correctly with a limitation that connecting to the email server for the action cannot be achieve.

**Comment by dougmorris** [comment]
This has been resolved. Essentially surveys that had an anomaly fixed in the admin suite potentially caused a mis matching in the DB and a cached version of the survey in the survey manager. The survey Manager has been modified to pick up the changes from the DB.
