### ISSUE TITLE
.csv export (SMS Platform) is not happening in latest Chrome and IE

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-SMS-Services#2]
When we choose, .csv format to export the results in latest Chrome/IE, for the first time, it says network error, when we click on resume, it exports a csv file which contains HTML content.

Same works in Firefox.

**Comment by dougmorris** [comment]
A New version of the admin suite with be available to test tomorrow.

**Comment by dougmorris** [comment]
I am unable to replicate the problem - please recheck

**Comment by hitesh-opg** [comment]
Hi Doug,

It is still happening.

If you go any live survey > export and chose the csv option, download starts but it says network error, when we click on resume, it exports a csv file which contains HTML content.

**Comment by dougmorris** [comment]
@hitesh-opg  Please provide an example via skype so I can understand what it looks like.

**Comment by dougmorris** [comment]
@hitesh-opg is this still happening? I do not see the problem when I test.

**Comment by hitesh-opg** [comment]
This is resolved.
