### ISSUE TITLE
SMS are not being sent out, QA record shows anomaly

### ISSUE THREAD

**Issue by onepoint** [OnePointGlobal/OnePoint-Global-SMS-Services#26]
Example customerIDs are 39649459 and 39649460. The QA records suggest the survey started but most recent question is in status 6, however no SMS has been sent out.

**Comment by dougmorris** [comment]
I can confirm the answer - will be running the survey locally to check the problem.

**Comment by dougmorris** [comment]
This has now been fixed and released
