### ISSUE TITLE
Unexpected behaviour in SMS survey

### ISSUE THREAD

**Issue by onepoint** [OnePointGlobal/OnePoint-Global-SMS-Services#28]
The following customerIDs appear to show a pattern in the survey that is not expected:

31184335 - this customer replied to a question but the answer was stored against a question that had previously been answered. The correct question is showing an answer status of 5.

31184180 - this customer replied to a question but the next question was not sent out. The answer status suggests the system is still waiting for an answer.

**Comment by dougmorris** [comment]
My initial investigation shows that it is possible for the processing of a question to fail (between receiving the answer and sending out the next question/message) that could leave the status as 5. I need to consider what changes would be required to rectify this.

**Comment by onepoint** [comment]
Closing this bug because the problem has not occurred since it was raised.
