### ISSUE TITLE
Sign in link not present in the Start notification

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-SMS-Services#29]
Please see the below notification:

----------------------------------------
OnePoint Global
Survey Start Notification
----------------------------------------

Start_notifictation_test has started
To monitor results in real-time and view reports log in to:
/signin.aspx

[E] support@onepointglobal.com
[T] 0870 414 2625

**Comment by dougmorris** [comment]
This has been corrected. The following entry was missing from the config file:

    <add key="site.Path" value="http://www.onepointsurveys.com/surveys"/>
