### ISSUE TITLE
Action alerts are not working

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-SMS-Services#31]
Action alert is not working it throws error.

After checking the logs, we found that the database name is missing for the query.

**Comment by dougmorris** [comment]
@pavithra-opg please can you share the specific error.

**Comment by pavithra-opg** [comment]
@dougmorris Error message was "Service is current unavailable please try again later"

**Comment by dougmorris** [comment]
Thank for the information @pavithra-opg. The config has been update to include access to the SMS database.
