### ISSUE TITLE
GSM characters are considered as Unicode 

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-SMS-Services#33]
SMS sent are considered as Unicode while there are no Unicode characters in it.

Sharing one of many tranID's  157139 for further investigation.

**Comment by dougmorris** [comment]
@pavithra-opg  Looked in the DB and cannot see a problem. This is charged as 1 segment. Please confirm the DB and table you are referring to.

**Comment by dougmorris** [comment]
The message contains the character (’) which is unicode instead of a (') which is not unicode.
