### ISSUE TITLE
Time stamp not recorded for question having status as timed out

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-SMS-Services#34]
For one of our client project, time is not recorded in the export even if the delivery of the question is successful.

Please see the  screenshot (I have removed all the personal details for security reasons but you can use the customer id to investigate)

![time_stamp](https://user-images.githubusercontent.com/26539946/41035311-e5cc7eea-69a9-11e8-9a57-69a4b0ad9e2a.png)

In the screenshot you can see that for two ID's there is no entry for T2 even though as per logs Q2 was sent and delivered.
whereas  one of the ID is displaying Time for T2

The only difference in these ID's is that for the one's where there is no T2 recorded, the status of the question Q2 in QA table is Timed out
However, for the ID where T2 is recorded, the tatus of the question Q2 in QA table is waiting for answer

Based on the fact that no time is recorded (T2) the client is suspecting that the question Q2 was not deliverd.

So it is confusing why time is not recorded in this case, will be good to understand.

**Comment by dougmorris** [comment]
@hitesh-opg what application is this from - DataIO or Admin Suite?

**Comment by onepoint** [comment]
It's an export from the admin suite.

**Comment by dougmorris** [comment]
I have run the report again and checked the results and all looks OK.
![image](https://user-images.githubusercontent.com/4094389/58893120-62859600-86e7-11e9-8344-43eb822c5a74.png)
Please close if you are happy to.

**Comment by hitesh-opg** [comment]
Thanks, @dougmorris, we will close this at this point as we have not come across the same scenario in recent times.
