### ISSUE TITLE
Discrepancy in credits remaining 

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-SMS-Services#35]
Credits remaining as per the message usage report is not matching the credits remaining in the account.
Details are shared separately via Slack.

**Comment by dougmorris** [comment]
@pavithra-opg is this still a problem?

**Comment by pavithra-opg** [comment]
@dougmorris,

Quick question, when we check for the credits remaining in an account using the admin credentials, there are two places which displays the credits. Below is the example of one account, where one place it shows negative and the other shows the actual credits(highlighted in red):

![image](https://user-images.githubusercontent.com/28919270/59024697-1023b100-8870-11e9-8dd6-73f1af18dd0c.png)

![image](https://user-images.githubusercontent.com/28919270/59024584-d488e700-886f-11e9-8bd4-736759e5b084.png)

Can this be corrected?

Also, when we signin to the account and want to check for the credits remaining in my account, there is no way I can access the credit usage page but rather just displays a credit which isn't the correct one.

In case of any questions, please let me know.

**Comment by dougmorris** [comment]
Hi @pavithra-opg,
This is due to balances not being right at the point the transactions begin to be recorded. It cannot be corrected directly, but with an amendment through the Add Credits feature it can be recorded as an adjustment to the balance for the account.

**Comment by dougmorris** [comment]
@pavithra-opg is this still an issue?

**Comment by onepoint** [comment]
There is no issue @dougmorris - the changes to the way the credit summary feature worked versus the older credit balance, relating the discrepancy, were not understood at the time. Now that we have been working with the new feature for some time it is clearer how the feature works and why that discrepancy exists.

It would still be ideal to release a cutdown version of the credit summary feature to the public-facing side of the account and then remove the old credit balance feature.

**Comment by dougmorris** [comment]
> It would still be ideal to release a cutdown version of the credit summary feature to the public-facing side of the account and then remove the old credit balance feature.

@onepoint  Please elaborate!

**Comment by onepoint** [comment]
Elaboration =

![image](https://user-images.githubusercontent.com/2592805/68859753-e2287f80-06df-11ea-8e72-d73bb5eb8d9a.png)


And then....

![image](https://user-images.githubusercontent.com/2592805/68859540-6595a100-06df-11ea-920a-e73d59923fef.png)

**Comment by dougmorris** [comment]
@onepoint This is in place on staging for testing.

**Comment by onepoint** [comment]
Looks fine @dougmorris can you provide the release details for live please.

**Comment by dougmorris** [comment]
@onepoint is this going to be closed?

**Comment by pavithra-opg** [comment]
@dougmorris I am closing this request
