### ISSUE TITLE
SMS were not sent out for live survey(s)

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-SMS-Services#37]
For one of the client the surveys were live, however, the messages were not being sent.

For one of the survey around 34 messages out of 100 were not sent

For another all 25 messages were not sent

None of the numbers were part of the opt-out list and Active number table showed the numbers were part of the correct survey.

On inspection, we found  the survey manager is not starting the clean-up for live surveys (log files are shared separately)

To resolve the issue, we re-started the SRS service but it will be good to check why the the clean-up did not work.

**Comment by dougmorris** [comment]
This has now been fixed.
