### ISSUE TITLE
Anomalies in Mandatory Rating Question 0-10

### ISSUE THREAD

**Issue by James-OPG** [OnePointGlobal/OnePoint-Global-SMS-Services#38]
There's an issue with anomalies in a "mandatory" 0-10 rating question, whereby the 0 is not recorded as a valid answer and is instead recorded as an anomaly.  Please see slack SMS channel posting from me dated June 13 2018 for pictures of anomalies + examples.

**Comment by dougmorris** [comment]
Mandatory rating questions using a slider had a change to make it an anomaly if the slider was left at the minimum value. this has been changed to not make the minimum value an anomaly. Awaiting feedback from Mark.

**Comment by onepoint** [comment]
This is resolved with the customer logic being put back in place.
