### ISSUE TITLE
SMS being sent even if a survey is abandoned

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-SMS-Services#39]
Even after abandoning a survey, invites were sent out.

This issue seems to happen for surveys where the recipients are added via automated import and '**when**' field is specified for the sample.

The details of the survey are :

surveyid: 560122

customerlistid: 33274

customerID : 40040029 (This customer got the SMS after the survey was abandoned)

This is a high priority issue as it has the potential to impact many customers

**Comment by dougmorris** [comment]
This has now been fixed.
