### ISSUE TITLE
SMS API not updating receipts

### ISSUE THREAD

**Issue by onepoint** [OnePointGlobal/OnePoint-Global-SMS-Services#40]
It appears that some receipt updates are not being saved in the database. Some examples of receiptIDs are:

209900344 (China)
Web service log: **06/11/2018 08:55:04**||False|True|%&^RECEIPTMESSAGE%^&|True|0|_hidden_:S209900344|2|1
DB lastupdate: **2018-11-06 06:24:47.190**

209888571 (Italy)
**06/11/2018 08:44:04**||False|True|%&^RECEIPTMESSAGE%^&|True|0|_hidden_:S209888571|2|1
DB lastupdate: **2018-11-05 17:40:38.050**

209882611 (Global)
**06/11/2018 07:04:05**||False|True|%&^RECEIPTMESSAGE%^&|True|3|_hidden_:S209882611|2|1
DB lastupdate: **2018-11-05 06:03:12.053**

In the cases above the receipt is created correctly but not modified when the web service receives a receipt update.

The log files for these transactions will be provided separately.

**Comment by dougmorris** [comment]
@onepoint:
I have checked these and they all appear in the DB and have all been successfully processed.
