### ISSUE TITLE
Password Reset Instructions Inaccurate on www.onepointsurveys.com

### ISSUE THREAD

**Issue by James-OPG** [OnePointGlobal/OnePoint-Global-SMS-Services#42]
Current password reset instructions read: You must enter a new password and confirm it to get back in the OnePoint service. You must use a combination of lowercase, uppercase, numerics and special characters such as &, $, and @. The password must be at least 8 characters long. If you continue to have problems please email support@onepointglobal.com.

Which does not correctly reflect the scope of acceptable passwords.  The ONLY acceptable special characters as of now are &,$,@ - suggest either improving the list of special characters accepted during password reset to the entire list of symbols on standard keyboards 

> `~!@#$%^&*()_+-=\][|}{';":/.,?><

 or replace the instructions to reflect acceptable password parameters.   Example below:

You must enter a new password and confirm it to resume using OnePoint SMS services. Your password must be at least 8 characters long and include one lowercase character, one uppercase character, one number, and one of the following special characters: &, $, @.  If you continue to have problems please email support@onepointglobal.com.

**Comment by dougmorris** [comment]
@James-OPG available on staging for testing.

**Comment by James-OPG** [comment]
Has the staging URL changed?  Having issues accessing it to test this one.

![image](https://user-images.githubusercontent.com/28926171/65548136-e5299f80-dee8-11e9-91df-c3e580550dcf.png)

**Comment by dougmorris** [comment]
Hi @James-OPG, apologies, this problem is now resolved.

**Comment by dougmorris** [comment]
Any update @James-OPG?

**Comment by James-OPG** [comment]
@dougmorris Tried pulling it up but not receiving the password reset email.

**Comment by dougmorris** [comment]
thanks @James-OPG, will investigate

**Comment by dougmorris** [comment]
@James-OPG, tested the live platform with my own account and got a reset email....
![image](https://user-images.githubusercontent.com/4094389/68582280-4514df00-0472-11ea-9a4e-3eacd5da8185.png)

**Comment by James-OPG** [comment]
@dougmorris This was on staging, not live.  I've confirmed I'm still not receiving the password reset email on Staging.  Have the password reset instructions been released to live?

**Comment by dougmorris** [comment]
The email server in the web.config for the service on staging was pointing to a live server.

`    <add key="email.ServerAddress" value="10.10.12.51" />`

**Comment by James-OPG** [comment]
Looks good @dougmorris - accepting all special characters now.

**Comment by dougmorris** [comment]
@James-OPG  ok - will provide a release package for you.

**Comment by James-OPG** [comment]
@dougmorris Good stuff!  It's live and working.
