### ISSUE TITLE
SMS Transactions Associated to Incorrect SurveyID

### ISSUE THREAD

**Issue by onepoint** [OnePointGlobal/OnePoint-Global-SMS-Services#43]
Various tables (details can be provided if required) are updated with an inaccurate surveyID value based on the way the cost rollup service is working. This inaccuracy then filters through reporting since it appears as though SMS transactions are associated to a different account.

To explain the reason for the inaccuracy:

If a tranlog record has zero for the surveyID field the cost rollup service will try to match the destination number to a previously associated surveyID if there is one. This behaviour is acceptable in some cases but if that tranlog record relates to an SMS submitted via the API then there will be no surveyID. If that destination has previously been used in a survey by any customer ever then that surveyID is used.

Is there a way to improve the cost rollup service to cater for SMS submitted via the API?

**Comment by onepoint** [comment]
Here is an example customerID: 43057241

**Comment by dougmorris** [comment]
@onepoint I have a change available that will not allocate messages to surveys that are sent through the API and  go straight to the gateway and not through the message manager.

**Comment by dougmorris** [comment]
@onepoint please confirm and close. In addition it is possible to update all old MessageTran, based on their associated TranLog entries containing a surveyID of '0'.

**Comment by onepoint** [comment]
@dougmorris I am monitoring the tranlog table waiting for an entry that has a zero for the surveyid field but there hasn't been one yet. I am not sure how to replicate this either, each time I try to send an SMS via the API it puts the gatewaytranID value into the field, e.g. "M:14159025".

**Comment by dougmorris** [comment]
@onepoint you need to make sure that the route the message takes is directly to the gateway as opposed to the gatewaytran table first. this is controlled by the routing tables in the zone file.

**Comment by onepoint** [comment]
@dougmorris I can confirm the fix is working correctly. 

Looking at the zone file it would appear that all messages go via the message gateway so I am confused about how an SMS is ever sent out directly via the gateway. Is there a scenario this would happen by design?

**Comment by dougmorris** [comment]
@onepoint I will check the zone file and come back to you

**Comment by dougmorris** [comment]
@onepoint currently the code is such that it searches for a route based on the main gateways and if these do not match it used the message connection. Checking the transactions seems to confirm this.

**Comment by onepoint** [comment]
> @onepoint you need to make sure that the route the message takes is directly to the gateway as opposed to the gatewaytran table first. this is controlled by the routing tables in the zone file.

@dougmorris what is the difference between searching for "a route based on the main gateways" and the SMS being sent "directly to the gateway" in terms of the routing setup? I'm still uncertain about why these SMS would have been sent directly to the gateway (zero surveyID) in the first place and where the routing is that defines this behaviour.

**Comment by dougmorris** [comment]
@onepoint I will update the documentation in due course. As previously explained, if the route is found in the main gateways then they are used, otherwise the message manager is used. There is no difference between send directly and routing based on the main gateways. the standard routing that has been defined defines this behaviour. 

If you are looking for something else then happy to help. In the mean time is this issue closed as the main issue was to do with the SurveyID?

**Comment by onepoint** [comment]
Yes a quick conversation outside this thread will solve my confusion. Happy to close this issue since the problem appears to be resolved.
