### ISSUE TITLE
Assign a senderID to an SMS based on a customer field

### ISSUE THREAD

**Issue by onepoint** [OnePointGlobal/OnePoint-Global-SMS-Services#44]
To improve the efficiency of the platform and allow for a single survey to cater for multiple brands it would be good to allow the SenderID of an SMS to be included as part of the customer record. 

This would require changes to support the survey container being setup to include a macro for the senderID field rather than a string. When the survey is then launched the macro would relate to the field in the customer record that contains the senderID to be used for that respondent.

This means the validation rules may no longer apply since the platform will not be aware of the senderID, meaning greater control and vigilance will be required when using this feature.

**Comment by dougmorris** [comment]
@onepoint when a survey is setup there is a SenderID value that can be defined. This can be a macro; for example: ${user1}. The message being sent is a branded message or no reply then it will use this value and convert the macro as required.

**Comment by onepoint** [comment]
I've tested this and can confirm it works perfectly. Thanks @dougmorris!
