### ISSUE TITLE
SMS response is not triggering the next question in a survey

### ISSUE THREAD

**Issue by onepoint** [OnePointGlobal/OnePoint-Global-SMS-Services#9]
Customerid 39588633 shows a response was received but the shotgun dismissed the response.

**Comment by dougmorris** [comment]
This is correct - the survey is no longer live - it expired on Sunday and the text came in today.

**Comment by onepoint** [comment]
See customerid 39612004 instead as a valid example.

**Comment by dougmorris** [comment]
After further investigation a problem with the survey manager in a multi survey environment resulted in answers to questions being unpredictably processed by different surveys, resulting in the message - 2018-04-16 15:45:07 - [85] ERROR InterviewSession - SurveyService is unable to process the message from [xxxxxxxx].

This has now been resolved.
